name: SemVer release vars
description: "Compute SemVer release vars."
author: "julbme"
branding:
  icon: terminal
  color: blue
inputs:
  package_version:
    description: "The release version defined in the package."
    required: true
outputs:
  version:
    description: "The release version."
  version_major:
    description: "The release version major value."
  version_minor:
    description: "The release version minor value."
  version_patch:
    description: "The release version patch value."
  version_suffix:
    description: "The release version suffix value."
  version_build:
    description: "The release version build value."
  git_tag:
    description: "The git tag for that version."
  git_tag_major:
    description: "The git tag with major version only if the release version is the latest in major scope"
  git_tag_minor:
    description: "The git tag with major/minor version only if the release version is the latest in major/minor scope."
  git_tag_patch:
    description: "The git tag with major/minor/patch version only if the release version is the latest in major/minor/patch scope."
  docker_tag:
    descrption: The Docker tag for that version."
  docker_tag_major:
    description: "The Docker tag with major version only if the release version is the latest in major scope."
  docker_tag_minor:
    description: "The Docker tag with major/minor version only if the release version is the latest in major/minor scope."
  docker_tag_patch:
    description: "The Docker tag with major/minor/patch version only if the release version is the latest in major/minor/patch scope."
  next_major_version:
    description: "If major-incremented, the next version."
  next_minor_version:
    description: "If minor-incremented, the next version."
  next_patch_version:
    description: "If patch-incremented, the next version."
  next_major_snapshot_version:
    description: "If major-incremented, the next version with SNAPSHOT suffix."
  next_minor_snapshot_version:
    description: "If minor-incremented, the next version with SNAPSHOT suffix"
  next_patch_snapshot_version:
    description: "If patch-incremented, the next version with SNAPSHOT suffix."
  trigger_branch:
    description: "The branch which triggered the release."
  trigger_branch_ref:
    description: "The branch ref which triggered the release."
  run_branch:
    descrption: "The temporary branch in which release commits can be pushed before being merged in target branch."
  run_branch_ref:
    description: "The temporary branch ref in which release commits can be pushed before being merged in target branch."
  target_branch:
    description: "The target branch in which release commits should be merged if successful. It will try to resolve the corresponding maintenance branch. If not found, it will use the project default branch."
  target_branch_ref:
    description: "The target branch in which release commits should be merged if successful. It will try to resolve the corresponding maintenance branch. If not found, it will use the project default branch."

runs:
  using: "docker"
  image: "Dockerfile"
